### ISSUE TITLE
Test failures are breaking master

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-google-analytics#1]
As noted in https://github.com/segmentio/analytics.js-integrations/issues/645:

> Google Analytics changed some internal implementation details and now our tests are failing, causing the entire project to fail. These tests don't actually indicate a failure of the integration, but rather an inappropriate intimacy problem in our tests.
> 
> Tests should be refactored to test the GA interface, not its internal mechanisms.

These tests are pretty much cosmetic right now but should be fixed as they could mask real errors

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!
