### ISSUE TITLE
ability to set path in the track() method

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-google-analytics#3]
_From @TimmyCarbone on October 27, 2014 16:7_

Currently, we can set the `path` property in the `page()` method and it sets GA's `pagePath` property. 

It would be good for consistency to be able to set GA's `pagePath` in the `track()` method too.
We can set the `path` property but it won't affect GA's `pagePath`.

To summarize, the virtual path doesn't work on GA events. Currently, events and pageviews can't be associated through the `path`.

Should be something around there : 
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L207

with a property like this : 
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L173

_Copied from original issue: segmentio/analytics.js-integrations#442_

**Comment by ndhoule** [comment]
_From @j0rd on October 29, 2014 13:13_

I'm using analytics.js on single page webapp. Using Google Analytics and Mixpanel.

Google Analytics requires /paths to make goal funnels work, MixPanel can rely on events.

To satisfy both, I'm tracking my funnel "page views /  events" like this:

```
analytics.page('Song Upload Started', {                                                                                                                               
    'category': 'Song Upload',                                                                                                                                          
    'label': theBand.name + ' [' + theBand.id + ']',                                                                                                                    
    'path': '/modal/songupload/step1/uploading',                                                                                                                        
    'url': theuri() + '/modal/songupload/step1/uploading',                                                                                                         
    'Band ID': theBand.id,                                                                                                                                              
  });                                                                                                                                                                   
});
```

This triggers both a Page View (what I need for GA) and an Event in Mixpanel.

But what I've noticed is that while my pageviews are tracked appropriately in GA, that the GA events are not tracked appropriately with the virtual page view.

Analytics.js should be sending the page along with the events like this:

```
ga('send', 'event', 'category', 'action', {'page': '/my-new-page'});
```

Here's the GA field def for 'page' (which mention it works with event)
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hitType

**Comment by hankim813** [comment]
closed for inactivity. please reopen if this is still an issue
