### ISSUE TITLE
Spec: V2 Ecommerce Events - Missing Product Product List Viewed and Product List Filtered

### ISSUE THREAD

**Issue by nickrathwell** [segment-integrations/analytics.js-integration-google-analytics#34]
Cannot find any ecommerce tracking in index.js that as code for https://segment.com/docs/spec/ecommerce/v2/#product-list-viewed or https://segment.com/docs/spec/ecommerce/v2/#product-list-filtered

These would need to map to https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#product-impression

Was this left out on purpose if yes why?

Thanks
Nick

**Comment by nickrathwell** [comment]
@SegmentBot a reply on this would be appreciated.
Thanks,
Nick

**Comment by sperand-io** [comment]
Hey Nick — ditto #35: this was not left out on purpose, but was added to the spec without adding support in the integration. Will leave this open until we get a chance to get the integration up to spec.

**Comment by Peripheral1994** [comment]
Closed by https://github.com/segment-integrations/analytics.js-integration-google-analytics/pull/46
